# Generated by Django 5.2 on 2025-04-13 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_criação', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=255)),
                ('descripition', models.TextField()),
                ('duracao', models.PositiveIntegerField()),
                ('ativo', models.BooleanField()),
                ('alunos', models.ManyToManyField(related_name='cursos', to='contrib.aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='contrib.professor')),
            ],
        ),
    ]
