# Generated by Django 5.2 on 2025-04-14 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gratuito',
            fields=[
                ('curso_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curso.curso')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('curso.curso',),
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='curso',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='curso',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
