# Generated by Django 5.2 on 2025-04-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_gratuito_alter_curso_options_curso_polymorphic_ctype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='price',
        ),
        migrations.AlterField(
            model_name='curso',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
