# Generated by Django 5.2 on 2025-04-14 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_remove_curso_price_alter_curso_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('curso_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curso.curso')),
                ('price', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('curso.curso',),
        ),
    ]
