# Generated by Django 5.2 on 2025-04-14 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0001_initial'),
        ('curso', '0006_alter_curso_alunos_alter_curso_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='alunos',
            field=models.ManyToManyField(blank=True, null=True, related_name='cursos', to='contrib.aluno'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='contrib.professor'),
        ),
    ]
